version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR... 
      - aws --version
      - aws ecr get-login-password --region ap-south-1
      - REPOSITORY_URI="396674985897.dkr.ecr.ap-south-1.amazonaws.com/nodedockerbuild"
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t 396674985897.dkr.ecr.ap-south-1.amazonaws.com/nodedockerbuild:latest .
      - docker tag 396674985897.dkr.ecr.ap-south-1.amazonaws.com/nodedockerbuild:latest 396674985897.dkr.ecr.ap-south-1.amazonaws.com/nodedockerbuild:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 396674985897.dkr.ecr.ap-south-1.amazonaws.com/nodedockerbuild:latest
      - echo Writing image definitions file...
      - cat imagedefinitions.json 
artifacts:
    files: imagedefinitions.json
